<script>
  // import LibraryStats from "../components/Widgets/LibraryStats.svelte";
  // import GenreTags from "../components/Widgets/GenreTags.svelte";
  // import Slidy from "../components/Widgets/Slidy.svelte";
  import ScreenHeader from "../components/Root/ScreenHeader.svelte";
  import AnotherVirtualScrollList from "../components/Virtual/AnotherVirtualScrollList.svelte";
  import NewVirtualScrollList from "../components/Virtual/NewVirtualScrollList.svelte";
  import { playerStore } from "../store/player";
  import VirtualScrollList from "./VirtualScrollList.svelte";

  let filter = "";
  $: items = $playerStore.filter((i) => i.fileLocation.includes(filter));

  const things = [
    // these can be any values you like
    { name: "one", number: 1 },
    { name: "two", number: 2 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "three", number: 3 },
    { name: "last", number: 10000 },
  ];
</script>

<!-- <VirtualScrollList itemCount={1000} height={300} childHeight={30} {items} /> -->

<!-- <NewVirtualScrollList height={"400px"} items={things} let:item>
  <p style="height: 50px;">{item.name} {item.number}</p>
</NewVirtualScrollList> -->

<AnotherVirtualScrollList
  width="100%"
  height={600}
  itemCount={things.length}
  itemSize={100}
>
  <div slot="item" let:index let:style {style}>
    <!-- Letter: {things[index]}, Row: #{index} -->
    {things[index].name}
    {things[index].number}
  </div>
</AnotherVirtualScrollList>

<style lang="scss">
</style>
